export const activities = [
  {
    id: 'photo-walk',
    title: '사진 산책',
    description: '저녁빛을 관찰하며 캠퍼스를 걷습니다.',
    category: 'hobby',
    capacity: 12,
    joined: 7,
    startsAt: '2026-09-07T18:00:00+09:00',
    tags: ['photo', 'walk'],
  },
  {
    id: 'web-study',
    title: '웹 표준 읽기',
    description: 'HTML과 접근성 문서를 함께 읽고 예제를 비교합니다.',
    category: 'study',
    capacity: 10,
    joined: 10,
    startsAt: '2026-09-03T17:00:00+09:00',
    tags: ['web', 'html'],
  },
  {
    id: 'algorithm-talk',
    title: '알고리즘 설명 모임',
    description: '작은 문제의 여러 풀이와 복잡도를 말로 설명합니다.',
    category: 'study',
    capacity: 16,
    joined: 9,
    startsAt: '2026-09-05T14:00:00+09:00',
    tags: ['algorithm', 'talk'],
  },
  {
    id: 'river-cleanup',
    title: '하천 정리 봉사',
    description: '안전 안내 후 산책로 주변을 함께 정리합니다.',
    category: 'volunteer',
    capacity: 20,
    joined: 12,
    startsAt: '2026-09-12T09:00:00+09:00',
    tags: ['walk', 'cleanup'],
  },
  {
    id: 'board-game',
    title: '보드게임 저녁',
    description: '처음 참여하는 사람도 규칙을 배우며 함께 게임합니다.',
    category: 'hobby',
    capacity: 8,
    joined: 5,
    startsAt: '2026-09-04T19:00:00+09:00',
    tags: ['game', 'social'],
  },
  {
    id: 'js-functions',
    title: 'JavaScript 함수 연습',
    description: '배열 데이터와 작은 순수 함수를 함께 검증합니다.',
    category: 'study',
    capacity: 14,
    joined: 6,
    startsAt: '2026-09-08T16:00:00+09:00',
    tags: ['web', 'javascript'],
  },
  {
    id: 'campus-guide',
    title: '새내기 캠퍼스 안내',
    description: '건물 위치와 이용 팁을 새내기에게 소개합니다.',
    category: 'volunteer',
    capacity: 18,
    joined: 18,
    startsAt: '2026-09-02T13:00:00+09:00',
    tags: ['guide', 'walk'],
  },
  {
    id: 'sketch-hour',
    title: '한 시간 스케치',
    description: '좋아하는 캠퍼스 풍경을 관찰하고 그립니다.',
    category: 'hobby',
    capacity: 15,
    joined: 3,
    startsAt: '2026-09-10T15:00:00+09:00',
    tags: ['art', 'walk'],
  },
];
