create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;

grant select on table public.posts to anon, authenticated;
grant insert, update, delete on table public.posts to authenticated;
grant usage, select on sequence public.posts_id_seq to authenticated;

drop policy if exists "posts are publicly readable" on public.posts;
create policy "posts are publicly readable"
on public.posts for select
to anon, authenticated
using (true);

drop policy if exists "users insert own posts" on public.posts;
create policy "users insert own posts"
on public.posts for insert
to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "users update own posts" on public.posts;
create policy "users update own posts"
on public.posts for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "users delete own posts" on public.posts;
create policy "users delete own posts"
on public.posts for delete
to authenticated
using ((select auth.uid()) = owner_id);
