create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 200),
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;
alter table public.comments enable row level security;

grant select on public.posts, public.comments to anon, authenticated;
grant insert, update, delete on public.posts, public.comments to authenticated;
grant usage, select on sequence public.posts_id_seq, public.comments_id_seq to authenticated;

drop policy if exists "read posts" on public.posts;
create policy "read posts" on public.posts
for select to anon, authenticated using (true);

drop policy if exists "insert own posts" on public.posts;
create policy "insert own posts" on public.posts
for insert to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "update own posts" on public.posts;
create policy "update own posts" on public.posts
for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "delete own posts" on public.posts;
create policy "delete own posts" on public.posts
for delete to authenticated
using ((select auth.uid()) = owner_id);

drop policy if exists "read comments" on public.comments;
create policy "read comments" on public.comments
for select to anon, authenticated using (true);

drop policy if exists "insert own comments" on public.comments;
create policy "insert own comments" on public.comments
for insert to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "delete own comments" on public.comments;
create policy "delete own comments" on public.comments
for delete to authenticated
using ((select auth.uid()) = owner_id);
